id = "blossom"
name = "Blossom"
version = "0.0.1"
schema_version = 1
authors = ["Felipe Hamm <me@felipehamm.com>"]
description = "Language support for the Blossom programming language"
repository = "https://github.com/fhamm/blossom"

[grammars.blossom]
repository = "https://github.com/fhamm/blossom"
path = "tools/tree-sitter"
commit = "669f04b4d75a6d44ec812cc8eb261d28ac16ef51"
